-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Kilometer" ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Labor" ALTER COLUMN "cost" DROP DEFAULT,
ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Material" ALTER COLUMN "cost" DROP DEFAULT,
ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "NextService" ALTER COLUMN "reason" DROP DEFAULT,
ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Service" ALTER COLUMN "cost" DROP DEFAULT,
ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT,
ALTER COLUMN "reason" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ServiceState" ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Vehicle" ALTER COLUMN "createdOn" SET DEFAULT '',
ALTER COLUMN "createdOn" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedOn" SET DEFAULT '',
ALTER COLUMN "modifiedOn" SET DATA TYPE TEXT;
